### ISSUE TITLE
Issue with using "Next Procedure" with a Command

### ISSUE THREAD

**Issue by SeaRoll** [SeaRoll/ZiboCopilot#3]
When calling for the next procedure function with a command (keyboard input), the procedure does not work...?

**Comment by Najsr** [comment]
Try the latest build (1.0.5), works fine for me.

**Comment by SeaRoll** [comment]
aha. will try

**Comment by Najsr** [comment]
Btw I've created a development branch. So we better use it for new code (testing etc...) before releasing it to the master branch
