### ISSUE TITLE
Enhancement request - Some action feedback

### ISSUE THREAD

**Issue by JAdata** [SeaRoll/ZiboCopilot#9]
Great plugin! I would wish for some kind of feedback back to "the pilot" on what the co-pilot is doing - e.g. a text box displaying "Turning battery on"..."Enabling IRS"..."Starting APU"... - just a small feedback on each step taken during the procedures. Now there's only a "talk" at the beginning of the procedures, and one at the end and silence in between... Speaking out each action may be to "noisy" and time consuming...

**Comment by SeaRoll** [comment]
Can add as a option later in development :) ATM it's not the highest priority (trying to fix up the code hehe)

I will keep this issue open to keep in my mind
